<!DOCTYPE html>
                              <html lang="en">
                              <head>
                                <meta charset="UTF-8">
                                <meta http-equiv="X-UA-Compatible" content="IE=edge">
                                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                                <style>* { box-sizing: border-box; } body {margin: 0;}*{box-sizing:border-box;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;font-family:"Open Sans", sans-serif;}body{margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;}.input:focus + .label, .input:active + .label, .input.filled + .label{font-size:0.75rem;transition-duration:0.2s;transition-timing-function:ease-out;transition-delay:0s;transition-property:all;top:-0.9rem;background-color:rgb(255, 255, 255);color:rgb(26, 115, 232);padding-top:0px;padding-right:5px;padding-bottom:0px;padding-left:5px;margin-top:0px;margin-right:5px;margin-bottom:0px;margin-left:5px;}#i2jwl{padding:10px;}</style>
                                <title></title>
                                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2/dist/tailwind.min.css" type="text/css" />
                              </head>
                              <body id="iwgg"><meta charset="UTF-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>mfa</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2/dist/tailwind.min.css" type="text/css"/><meta charset="UTF-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>MFA</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2/dist/tailwind.min.css" type="text/css"/><div id="i2jwl"><b>MFA Auth</b></div></body>
                              </html>